#include "events/public/event.h"

#include <unordered_map>

namespace muse
{

std::unordered_map<Key, KeyState> keymap = {
    {Key::NUM_0, KeyState::UP},
    {Key::NUM_1, KeyState::UP},
    {Key::NUM_2, KeyState::UP},
    {Key::NUM_3, KeyState::UP},
    {Key::NUM_4, KeyState::UP},
    {Key::NUM_5, KeyState::UP},
    {Key::NUM_6, KeyState::UP},
    {Key::NUM_7, KeyState::UP},
    {Key::NUM_8, KeyState::UP},
    {Key::NUM_9, KeyState::UP},
    {Key::A, KeyState::UP},
    {Key::B, KeyState::UP},
    {Key::C, KeyState::UP},
    {Key::D, KeyState::UP},
    {Key::E, KeyState::UP},
    {Key::F, KeyState::UP},
    {Key::G, KeyState::UP},
    {Key::H, KeyState::UP},
    {Key::I, KeyState::UP},
    {Key::J, KeyState::UP},
    {Key::K, KeyState::UP},
    {Key::L, KeyState::UP},
    {Key::M, KeyState::UP},
    {Key::N, KeyState::UP},
    {Key::O, KeyState::UP},
    {Key::P, KeyState::UP},
    {Key::Q, KeyState::UP},
    {Key::R, KeyState::UP},
    {Key::S, KeyState::UP},
    {Key::T, KeyState::UP},
    {Key::U, KeyState::UP},
    {Key::V, KeyState::UP},
    {Key::W, KeyState::UP},
    {Key::X, KeyState::UP},
    {Key::Y, KeyState::UP},
    {Key::Z, KeyState::UP},
    {Key::BACKSPACE, KeyState::UP},
    {Key::ENTER, KeyState::UP},
    {Key::DEL, KeyState::UP},
    {Key::ESCAPE, KeyState::UP},
    {Key::LCTRL, KeyState::UP},
    {Key::RCTRL, KeyState::UP},
    {Key::UP_ARROW, KeyState::UP},
    {Key::DOWN_ARROW, KeyState::UP},
    {Key::RIGHT_ARROW, KeyState::UP},
    {Key::LEFT_ARROW, KeyState::UP},
    {Key::LALT, KeyState::UP},
    {Key::RALT, KeyState::UP},
    {Key::LSHIFT, KeyState::UP},
    {Key::RSHIFT, KeyState::UP},
    {Key::CAPS_LOCK, KeyState::UP},
    {Key::F1, KeyState::UP},
    {Key::F2, KeyState::UP},
    {Key::F3, KeyState::UP},
    {Key::F4, KeyState::UP},
    {Key::F5, KeyState::UP},
    {Key::F6, KeyState::UP},
    {Key::F7, KeyState::UP},
    {Key::F8, KeyState::UP},
    {Key::F9, KeyState::UP},
    {Key::F10, KeyState::UP},
    {Key::F11, KeyState::UP},
    {Key::F12, KeyState::UP},
    {Key::TAB, KeyState::UP},
    {Key::LESS, KeyState::UP},
    {Key::GREATER, KeyState::UP},
    {Key::EQUALS, KeyState::UP},
    {Key::PLUS, KeyState::UP},
    {Key::MINUS, KeyState::UP},
    {Key::SLASH, KeyState::UP},
    {Key::BACKSLASH, KeyState::UP},
    {Key::SPACE, KeyState::UP},
    {Key::COLON, KeyState::UP},
    {Key::SEMICOLON, KeyState::UP},
    {Key::PERIOD, KeyState::UP},
    {Key::COMMA, KeyState::UP},
    {Key::LBRACE, KeyState::UP},
    {Key::RBRACE, KeyState::UP},
    {Key::LBRACKET, KeyState::UP},
    {Key::RBRACKET, KeyState::UP},
    {Key::ASTERISK, KeyState::UP},
    {Key::AMPERSAND, KeyState::UP},
    {Key::AT, KeyState::UP},
    {Key::HASHTAG, KeyState::UP},
    {Key::DOLLAR, KeyState::UP},
    {Key::LPAREN, KeyState::UP},
    {Key::RPAREN, KeyState::UP},
    {Key::PERCENT, KeyState::UP},
    {Key::EXCLAIM, KeyState::UP},
    {Key::DOUBLE_QUOTE, KeyState::UP},
    {Key::QUOTE, KeyState::UP}};

KeyState &KeyboardEvent::operator[](Key key) const
{
    return keymap[key];
}

KeyboardEvent::KeyboardEvent(Key key, KeyState state)
{
    keymap[key] = state;
}

}